import TForecastPeriod from "../../types/forecastPeriod";
const fakePeriods: TForecastPeriod[] = [
  {
    number: 1,
    name: "This Afternoon",
    startTime: "2022-03-30T14:00:00-07:00",
    endTime: "2022-03-30T18:00:00-07:00",
    isDaytime: true,
    temperature: 61,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 mph",
    windDirection: "SW",
    icon: "https://api.weather.gov/icons/land/day/few?size=medium",
    shortForecast: "Sunny",
    detailedForecast:
      "Sunny, with a high near 61. Southwest wind around 10 mph.",
  },
  {
    number: 2,
    name: "Tonight",
    startTime: "2022-03-30T18:00:00-07:00",
    endTime: "2022-03-31T06:00:00-07:00",
    isDaytime: false,
    temperature: 54,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "5 to 10 mph",
    windDirection: "SSE",
    icon: "https://api.weather.gov/icons/land/night/fog?size=medium",
    shortForecast: "Patchy Fog",
    detailedForecast:
      "Patchy fog between 11pm and 5am. Mostly cloudy, with a low around 54. South southeast wind 5 to 10 mph.",
  },
  {
    number: 3,
    name: "Thursday",
    startTime: "2022-03-31T06:00:00-07:00",
    endTime: "2022-03-31T18:00:00-07:00",
    isDaytime: true,
    temperature: 61,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "5 to 10 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/bkn?size=medium",
    shortForecast: "Partly Sunny",
    detailedForecast:
      "Partly sunny, with a high near 61. South wind 5 to 10 mph.",
  },
  {
    number: 4,
    name: "Thursday Night",
    startTime: "2022-03-31T18:00:00-07:00",
    endTime: "2022-04-01T06:00:00-07:00",
    isDaytime: false,
    temperature: 54,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "0 to 10 mph",
    windDirection: "SSW",
    icon: "https://api.weather.gov/icons/land/night/fog?size=medium",
    shortForecast: "Patchy Fog",
    detailedForecast:
      "Patchy fog after 11pm. Mostly cloudy, with a low around 54. South southwest wind 0 to 10 mph.",
  },
  {
    number: 5,
    name: "Friday",
    startTime: "2022-04-01T06:00:00-07:00",
    endTime: "2022-04-01T18:00:00-07:00",
    isDaytime: true,
    temperature: 62,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "5 to 15 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/fog/sct?size=medium",
    shortForecast: "Patchy Fog then Mostly Sunny",
    detailedForecast:
      "Patchy fog before 11am. Mostly sunny, with a high near 62. South wind 5 to 15 mph, with gusts as high as 20 mph.",
  },
  {
    number: 6,
    name: "Friday Night",
    startTime: "2022-04-01T18:00:00-07:00",
    endTime: "2022-04-02T06:00:00-07:00",
    isDaytime: false,
    temperature: 54,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "5 to 15 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/night/fog?size=medium",
    shortForecast: "Patchy Fog",
    detailedForecast:
      "Patchy fog after 11pm. Partly cloudy, with a low around 54.",
  },
  {
    number: 7,
    name: "Saturday",
    startTime: "2022-04-02T06:00:00-07:00",
    endTime: "2022-04-02T18:00:00-07:00",
    isDaytime: true,
    temperature: 63,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "5 to 15 mph",
    windDirection: "S",
    icon: "https://api.weather.gov/icons/land/day/fog?size=medium",
    shortForecast: "Patchy Fog",
    detailedForecast:
      "Patchy fog before 5pm. Partly sunny, with a high near 63.",
  },
  {
    number: 8,
    name: "Saturday Night",
    startTime: "2022-04-02T18:00:00-07:00",
    endTime: "2022-04-03T06:00:00-07:00",
    isDaytime: false,
    temperature: 55,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "5 to 15 mph",
    windDirection: "SSW",
    icon: "https://api.weather.gov/icons/land/night/fog?size=medium",
    shortForecast: "Patchy Fog",
    detailedForecast:
      "Patchy fog after 11pm. Mostly cloudy, with a low around 55.",
  },
  {
    number: 9,
    name: "Sunday",
    startTime: "2022-04-03T06:00:00-07:00",
    endTime: "2022-04-03T18:00:00-07:00",
    isDaytime: true,
    temperature: 62,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "5 to 15 mph",
    windDirection: "SSW",
    icon: "https://api.weather.gov/icons/land/day/fog/bkn?size=medium",
    shortForecast: "Patchy Fog then Mostly Cloudy",
    detailedForecast:
      "Patchy fog before 11am. Mostly cloudy, with a high near 62.",
  },
  {
    number: 10,
    name: "Sunday Night",
    startTime: "2022-04-03T18:00:00-07:00",
    endTime: "2022-04-04T06:00:00-07:00",
    isDaytime: false,
    temperature: 53,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "5 to 15 mph",
    windDirection: "NW",
    icon: "https://api.weather.gov/icons/land/night/bkn?size=medium",
    shortForecast: "Mostly Cloudy",
    detailedForecast: "Mostly cloudy, with a low around 53.",
  },
  {
    number: 11,
    name: "Monday",
    startTime: "2022-04-04T06:00:00-07:00",
    endTime: "2022-04-04T18:00:00-07:00",
    isDaytime: true,
    temperature: 65,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 to 15 mph",
    windDirection: "NW",
    icon: "https://api.weather.gov/icons/land/day/sct?size=medium",
    shortForecast: "Mostly Sunny",
    detailedForecast: "Mostly sunny, with a high near 65.",
  },
  {
    number: 12,
    name: "Monday Night",
    startTime: "2022-04-04T18:00:00-07:00",
    endTime: "2022-04-05T06:00:00-07:00",
    isDaytime: false,
    temperature: 56,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 to 15 mph",
    windDirection: "NNW",
    icon: "https://api.weather.gov/icons/land/night/few?size=medium",
    shortForecast: "Mostly Clear",
    detailedForecast: "Mostly clear, with a low around 56.",
  },
  {
    number: 13,
    name: "Tuesday",
    startTime: "2022-04-05T06:00:00-07:00",
    endTime: "2022-04-05T18:00:00-07:00",
    isDaytime: true,
    temperature: 69,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 to 15 mph",
    windDirection: "NW",
    icon: "https://api.weather.gov/icons/land/day/few?size=medium",
    shortForecast: "Sunny",
    detailedForecast: "Sunny, with a high near 69.",
  },
  {
    number: 14,
    name: "Tuesday Night",
    startTime: "2022-04-05T18:00:00-07:00",
    endTime: "2022-04-06T06:00:00-07:00",
    isDaytime: false,
    temperature: 57,
    temperatureUnit: "F",
    temperatureTrend: null,
    windSpeed: "10 to 15 mph",
    windDirection: "NNW",
    icon: "https://api.weather.gov/icons/land/night/few?size=medium",
    shortForecast: "Mostly Clear",
    detailedForecast: "Mostly clear, with a low around 57.",
  },
];

export default fakePeriods;
